version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    networks: ["hadoop"]
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    ports:
      - 50070:50070 # Web UI
      - 9000:9000   # HDFS
    env_file:
      - ./hadoop.env

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    networks: ["hadoop"]
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    env_file:
      - ./hadoop.env
  
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop2.7.4-java8
    container_name: resourcemanager
    networks: ["hadoop"]
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    ports:
      - 8088:8088 # UI
    env_file:
      - ./hadoop.env

  nodemanager1:
    image: dataops/nodemanager
    container_name: nodemanager1
    networks: ["hadoop"]
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    ports:
      - 8042:8042 # UI (logs access)
    env_file:
      - ./hadoop.env
  
  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop2.7.4-java8
    container_name: historyserver
    networks: ["hadoop"]
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    ports:
      - 8188:8188 # UI
    env_file:
      - ./hadoop.env

  hive-metastore:
    image: dataops/metastore
    container_name: hive-metastore
    networks: ["hadoop"]
    env_file:
      - ./hadoop.env
    volumes:
      - hive_metastore:/metastore
      - ./run-metastore.sh:/run-metastore.sh
    command: /run-metastore.sh
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    ports:
      - 9083:9083 # Thrift metastore

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    networks: ["hadoop"]
    env_file:
      - ./hadoop.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: ""
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - 10000:10000 # Thrift JDBC

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
  hive_metastore:

networks:
  hadoop:
    external:
      name: minicluster
