version: '3'

services:
  jupyter:
    image: dataops/jupyter:latest
    container_name: jupyter
    networks: ["hadoop"]
    volumes:
     - notebooks:/home/jovyan/work
    ports:
     - 8888:8888
     - 4040-4050:4040-4050
    env_file:
      - ./hadoop.env

networks:
  hadoop:
    external:
      name: minicluster

volumes:
  notebooks:

